name: CI/CD

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Testes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: npm
      - run: npm ci
      - run: npm test

  terraform:
    name: Terraform (plan/apply)
    needs: test
    runs-on: ubuntu-latest
    env:
      AWS_REGION: sa-east-1
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9"
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: sa-east-1

      - name: Terraform init
        run: terraform init
        working-directory: infra

      - name: Terraform format
        run: terraform fmt -check -recursive
        working-directory: infra

      - name: Terraform validate
        run: terraform validate
        working-directory: infra

      - name: Terraform plan
        run: terraform plan -input=false
        working-directory: infra

      - name: Terraform apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
        working-directory: infra